[IK-295] Member 도메인 Criteria 적용
prgrms-be-devcourse/BE-02-Instakyuram pull request #116
Opened 2022-07-04 16:22 UTC by whyWhale

## ✅  작업 단위

- [IK-295] Member 도메인 Criteria 적용

## 🤔 고민 했던 부분

- Validation @AssertTrue와 @AssertFalse로 검증을 할 수 있는 것은 다들 아실거라 생각합니다. 그런데 네이밍을 is- 로 prefix로 시작하지 않으면 @valid를 달아주어도 안되더군요! 
- 해당 부분을 꼭 기억하시면 좋을 것 같아 모두에게 공유 드립니다.
- @pjh612 진형님 member부분에 validation 유효성 검증의 네이밍을 MemberValidation 으로 변경하였습니다! 확인 한번 부탁드립니당

## 🔊 HELP !!

-

2022-07-04 16:57 UTC, pjh612 requested changes
고생하셨습니다~

2022-07-04 16:57 UTC, pjh612 commented on src/main/java/com/kdt/instakyuram/user/member/controller/MemberController.java
> +		return new ModelAndView("member/member-list").addObject(
가독성 측면에서 변수로 뺄 수 있는건 적당히 빼는것도 좋을 것 같습니다.

2022-07-04 16:57 UTC, pjh612 commented on src/main/java/com/kdt/instakyuram/user/member/domain/CustomMemberRepositoryImpl.java
> +		Root<Member> member = query.from(Member.class); // 애는 모지
머지 될때는 주석을 가급적 지우는게 좋을 것 같습니다.

2022-07-04 16:57 UTC, pjh612 commented on src/main/java/com/kdt/instakyuram/user/member/dto/MemberOrderDto.java
> +	public boolean isProper() {
'적절한' 이라는 의미로 쓰신 것 같은데 어떤 것이 적절한지 무엇을 기준으로 적절한지  메소드명으로 판단할 수 없는 것 같습니다.

2022-07-04 16:57 UTC, pjh612 commented on src/main/resources/application-local.yaml
> +    show-sql: ${SHOW_SQL:true}
설정을 바꿨다면 바꾼 이유에 대해서도 설명해주시면 좋을 것 같습니다. 커밋도 나누어져있는게 아니라 정확한 의도를 파악하기 어려울 것 같아요

2022-07-05 07:24 UTC, midasWorld approved these changes
고생하셨습니다! 👍

2022-07-05 07:24 UTC, midasWorld commented on src/main/resources/application.yaml
> +      expiry-seconds: 6000000
공용으로 사용 되는 설정값은 PR 내용에 있거나 따로 공유가 있으면 좋을 것 같습니다!

2022-07-05 07:41 UTC, HyoungUkJJang approved these changes
설정파일 변경된 내용 외에는 저도 의견을 남길 부분은 없는 것 같습니당 

고생하셨습니다 병연님 !

2022-07-05 12:07 UTC, HYEBPARK approved these changes
수고하셨습니당 !

2022-07-05 12:44 UTC, pjh612 approved these changes
고생하셨습니다.

2022-07-05 12:44 UTC, merged