[IK-29] 사용자가 팔로우 한 사람 목록을 조회한다.
prgrms-be-devcourse/BE-02-Instakyuram pull request #31
Opened 2022-06-19 13:15 UTC by whyWhale

## ✅  작업 단위

- [IK-29] 사용자가 팔로우 한 사람 목록을 조회한다.
  - [IK-94] 팔로잉 목록 기능 구현
  - [IK-95] 팔로잉 목록 조회 단위 테스트
  - [IK-141] 팔로잉 목록 조회 통합 테스트
  - [IK145] 팔로잉한 사용자 목록 단위 테스트 
  - [IK146] 팔로잉 멤버 목록 조회 통합 테스트
  - [IK-147] postGiver 연동 [post]

## 🤔 고민 했던 부분
### 기능 구현
- 현재는 팔로잉한 사람들을 모두 뽑아서 주지만 데이터 많아질 경우를 대비해서 limit에 대한 쿼리도 고민해야 한다고 생각합니다.
- 나중에 리팩터링 목록으로 가져가겠습니다.
- 현재 생각으로서는 네이티브 쿼리를 고려하고 있습니 🥕 !
- 네이티브 쿼리 말고 다른 방식이 있다면 추천 부탁드려 🐉

### 테스트 코드
- 해당 도메인 통합테스트에서 제공하는 모의 데이터는 EntityManager를 통해 영속화를 시키고 테스트를 진행했습니다.
- @Autowired 통해 다른 도메인 레포를 따로 두지 않는 것이 개인적으로 좋은 것 같아요. 
- 그 이유는 해당 도메인에 대해 통합 테스트를 하는데 다른 도메인 레포를 가지고 온 거 서부터가 레이어드 아키텍처가 깨져보일 수 있기 때문입니다.
- 실제 서비스는 레이어드로 가져가지만 테스트 코드 또한 레이어드 기반으로 테스트 되어야 한다고 생각합니 🥕 !

## 🔊 HELP !!

2022-06-19 15:40 UTC, pjh612 requested changes

2022-06-19 15:40 UTC, pjh612 commented on src/test/java/com/kdt/instakyuram/follow/IntegrationTest.java
> +public class IntegrationTest {
Integration Test 보다는 MemberServiceIntegrationTest가 검색을할때 검색결과 중복을 줄일 수 있어서 명확하게 가는게 좋을것 같습니다.

2022-06-19 15:40 UTC, pjh612 commented on src/main/java/com/kdt/instakyuram/member/service/MemberService.java
> +	public MemberResponse findById(Long id, ) {
',' 오타 수정 해주시면 감사하겠슴다~

2022-06-19 15:56 UTC, HYEBPARK approved these changes
병연님 수고하셨습니당 !

2022-06-19 15:56 UTC, HYEBPARK commented on src/test/java/com/kdt/instakyuram/follow/IntegrationTest.java
> +	EntityManager entityManager;
private 접근 제어자 선언 해둔 곳 안 해둔 곳 다 다른 것 같아용 
private 다 붙여주는 게 좋을 것 같습니당

2022-06-19 16:25 UTC, pjh612 approved these changes

2022-06-19 21:12 UTC, midasWorld approved these changes
고생하셨습니다. 👍

2022-06-20 00:36 UTC, HyoungUkJJang approved these changes
고생하셨습니다 병연님 !

2022-06-20 04:37 UTC, merged